import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.9.1:0',
  releaseNotes: {
    en_US:
      'Updates wisp to v0.9.1, which includes the v0.7.0 security release, v0.8.0 and v0.9.0. Fixes an authentication bypass: an AUTH event a user had signed for another relay could be altered to log in as that user here, and the same flaw affected the management API and protected events. Fixes requests that could crash the relay or pin a CPU core (an out of range limit or kind in a subscription, or a malformed sync message). Subscriptions with several filters now return matches from every filter, limit 0 returns no stored events as the protocol now requires, and multi-kind queries respect since and until. Private app data (NIP-78) is only stored for and served to its authenticated author. The management API gains the new unban, unallow and list methods, disallowkind now blocks a kind outright, and events synced from other relays follow the same bans, allowlists and limits as published ones. The relay is now built with Zig 0.17 and picks up two upstream WebSocket fixes. New in v0.9.0: gift-wrapped private messages (NIP-17 and NIP-59) are only served to their recipients, who must authenticate (NIP-42) to read them. Events synced from other relays are only stored if they come from or mention someone the relay follows, and mentions from unfollowed authors are rate limited per relay. The relay now runs as an unprivileged user instead of root; existing data is handed over automatically on first start. No settings change and no migration is needed.',
    es_ES:
      'Actualiza wisp a v0.9.1, que incluye la versión de seguridad v0.7.0, v0.8.0 y v0.9.0. Corrige una omisión de autenticación: un evento AUTH que un usuario había firmado para otro relé podía modificarse para iniciar sesión aquí como ese usuario, y el mismo fallo afectaba a la API de administración y a los eventos protegidos. Corrige solicitudes que podían bloquear el relé o dejar un núcleo de CPU al máximo (un límite o tipo fuera de rango en una suscripción, o un mensaje de sincronización mal formado). Las suscripciones con varios filtros devuelven ahora coincidencias de todos ellos, limit 0 no devuelve eventos almacenados como exige ahora el protocolo, y las consultas de varios tipos respetan since y until. Los datos privados de aplicaciones (NIP-78) solo se guardan para su autor autenticado y solo se le entregan a él. La API de administración incorpora los nuevos métodos para retirar prohibiciones, retirar permisos y listar, disallowkind ahora bloquea un tipo por completo, y los eventos sincronizados desde otros relés siguen las mismas prohibiciones, listas de permitidos y límites que los publicados. El relé se compila ahora con Zig 0.17 e incorpora dos correcciones de WebSocket de origen. Novedades de v0.9.0: los mensajes privados envueltos (NIP-17 y NIP-59) solo se entregan a sus destinatarios, que deben autenticarse (NIP-42) para leerlos. Los eventos sincronizados desde otros relés solo se guardan si proceden de alguien a quien el relé sigue o lo mencionan, y las menciones de autores no seguidos tienen un límite por relé. El relé se ejecuta ahora como un usuario sin privilegios en lugar de root; los datos existentes se le traspasan automáticamente en el primer arranque. No cambia ningún ajuste y no hace falta ninguna migración.',
    de_DE:
      'Aktualisiert wisp auf v0.9.1, das die Sicherheitsversion v0.7.0, v0.8.0 und v0.9.0 enthält. Behebt eine Umgehung der Authentifizierung: Ein AUTH-Ereignis, das ein Nutzer für ein anderes Relay signiert hatte, konnte so verändert werden, dass man sich hier als dieser Nutzer anmeldete; derselbe Fehler betraf die Verwaltungs-API und geschützte Ereignisse. Behebt Anfragen, die das Relay zum Absturz bringen oder einen CPU-Kern dauerhaft auslasten konnten (ein Limit oder eine Art außerhalb des gültigen Bereichs in einem Abonnement oder eine fehlerhafte Synchronisationsnachricht). Abonnements mit mehreren Filtern liefern jetzt Treffer aus allen Filtern, limit 0 liefert wie vom Protokoll nun verlangt keine gespeicherten Ereignisse, und Abfragen über mehrere Arten beachten since und until. Private App-Daten (NIP-78) werden nur für ihren authentifizierten Autor gespeichert und nur an ihn ausgeliefert. Die Verwaltungs-API erhält die neuen Methoden zum Aufheben von Sperren und Freigaben sowie zum Auflisten, disallowkind sperrt eine Art jetzt vollständig, und von anderen Relays synchronisierte Ereignisse unterliegen denselben Sperren, Freigabelisten und Grenzen wie veröffentlichte. Das Relay wird jetzt mit Zig 0.17 gebaut und übernimmt zwei WebSocket-Korrekturen aus dem Upstream. Neu in v0.9.0: Verpackte private Nachrichten (NIP-17 und NIP-59) werden nur an ihre Empfänger ausgeliefert, die sich zum Lesen authentifizieren müssen (NIP-42). Von anderen Relays synchronisierte Ereignisse werden nur gespeichert, wenn sie von jemandem stammen, dem das Relay folgt, oder ihn erwähnen, und Erwähnungen von nicht gefolgten Autoren sind pro Relay begrenzt. Das Relay läuft jetzt als Benutzer ohne Sonderrechte statt als root; vorhandene Daten werden beim ersten Start automatisch übergeben. Keine Einstellung ändert sich und es ist keine Migration nötig.',
    pl_PL:
      'Aktualizuje wisp do v0.9.1, które zawiera wydanie bezpieczeństwa v0.7.0, v0.8.0 oraz v0.9.0. Naprawia obejście uwierzytelniania: zdarzenie AUTH podpisane przez użytkownika dla innego przekaźnika można było zmodyfikować tak, by zalogować się tutaj jako ten użytkownik; ta sama luka dotyczyła API zarządzania i zdarzeń chronionych. Naprawia żądania, które mogły zawiesić przekaźnik lub trwale obciążyć rdzeń procesora (limit lub rodzaj spoza zakresu w subskrypcji albo niepoprawna wiadomość synchronizacji). Subskrypcje z wieloma filtrami zwracają teraz wyniki ze wszystkich filtrów, limit 0 zgodnie z obecnym wymogiem protokołu nie zwraca zapisanych zdarzeń, a zapytania o wiele rodzajów uwzględniają since i until. Prywatne dane aplikacji (NIP-78) są zapisywane i udostępniane wyłącznie ich uwierzytelnionemu autorowi. API zarządzania zyskuje nowe metody cofania blokad i zezwoleń oraz listowania, disallowkind blokuje teraz rodzaj całkowicie, a zdarzenia synchronizowane z innych przekaźników podlegają tym samym blokadom, listom dozwolonych i limitom co publikowane. Przekaźnik jest teraz budowany przy użyciu Zig 0.17 i zawiera dwie poprawki WebSocket z projektu źródłowego. Nowość w v0.9.0: opakowane prywatne wiadomości (NIP-17 i NIP-59) są udostępniane wyłącznie ich odbiorcom, którzy muszą się uwierzytelnić (NIP-42), aby je odczytać. Zdarzenia synchronizowane z innych przekaźników są zapisywane tylko wtedy, gdy pochodzą od kogoś obserwowanego przez przekaźnik lub go wspominają, a wzmianki od nieobserwowanych autorów mają limit na przekaźnik. Przekaźnik działa teraz jako użytkownik bez uprawnień administratora zamiast root; istniejące dane są przekazywane automatycznie przy pierwszym uruchomieniu. Żadne ustawienie się nie zmienia i nie jest potrzebna migracja.',
    fr_FR:
      "Met à jour wisp vers v0.9.1, qui inclut la version de sécurité v0.7.0, v0.8.0 et v0.9.0. Corrige un contournement de l'authentification : un événement AUTH qu'un utilisateur avait signé pour un autre relais pouvait être modifié pour se connecter ici sous son identité, et la même faille touchait l'API d'administration et les événements protégés. Corrige des requêtes qui pouvaient faire planter le relais ou monopoliser un cœur de processeur (une limite ou un type hors plage dans un abonnement, ou un message de synchronisation malformé). Les abonnements à plusieurs filtres renvoient désormais les correspondances de chaque filtre, limit 0 ne renvoie aucun événement stocké comme le protocole l'exige maintenant, et les requêtes sur plusieurs types respectent since et until. Les données privées d'applications (NIP-78) ne sont stockées et servies que pour leur auteur authentifié. L'API d'administration ajoute les nouvelles méthodes pour lever un bannissement, retirer une autorisation et lister, disallowkind bloque désormais un type entièrement, et les événements synchronisés depuis d'autres relais suivent les mêmes bannissements, listes d'autorisation et limites que ceux publiés. Le relais est désormais compilé avec Zig 0.17 et intègre deux correctifs WebSocket en amont. Nouveau dans v0.9.0 : les messages privés enveloppés (NIP-17 et NIP-59) ne sont servis qu'à leurs destinataires, qui doivent s'authentifier (NIP-42) pour les lire. Les événements synchronisés depuis d'autres relais ne sont stockés que s'ils proviennent d'une personne suivie par le relais ou la mentionnent, et les mentions d'auteurs non suivis sont limitées par relais. Le relais s'exécute désormais sous un utilisateur non privilégié au lieu de root ; les données existantes lui sont transférées automatiquement au premier démarrage. Aucun réglage ne change et aucune migration n'est nécessaire.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: async ({ effects }) => {},
  },
})
