import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.6.0:0',
  releaseNotes: {
    en_US:
      'Updates wisp to v0.6.0, skipping v0.5.15 which was never packaged. Adds a watchdog that restarts the relay if its accept loop ever stops accepting connections. Fixes several cases where the relay reported an incomplete answer as a complete one: a failed database read ended a query as though it had finished, and a negentropy sync could seal a partial set, which made the relay report events as missing that it actually held. Settings that could never take effect are now refused at startup with a warning naming them instead of being accepted silently, which matters most for the IP deny list, where an entry written as a CIDR range blocked nothing at all. Negentropy sync over large event sets is substantially faster, and a connection whose write fails is now closed instead of being left to receive a corrupted stream.',
    es_ES:
      'Actualiza wisp a v0.6.0, omitiendo v0.5.15 que nunca se empaquetó. Añade un vigilante que reinicia el relé si su bucle de aceptación deja de aceptar conexiones. Corrige varios casos en los que el relé informaba una respuesta incompleta como completa: una lectura fallida de la base de datos terminaba una consulta como si hubiera concluido, y una sincronización negentropy podía sellar un conjunto parcial, lo que hacía que el relé informara como ausentes eventos que sí tenía. Los ajustes que nunca podrían surtir efecto ahora se rechazan al iniciar con una advertencia que los nombra, en lugar de aceptarse en silencio; esto importa sobre todo en la lista de IP denegadas, donde una entrada escrita como rango CIDR no bloqueaba nada. La sincronización negentropy sobre conjuntos grandes de eventos es mucho más rápida, y una conexión cuya escritura falla ahora se cierra en lugar de quedar recibiendo un flujo corrupto.',
    de_DE:
      'Aktualisiert wisp auf v0.6.0 und überspringt v0.5.15, das nie paketiert wurde. Fügt einen Watchdog hinzu, der das Relay neu startet, falls seine Accept-Schleife keine Verbindungen mehr annimmt. Behebt mehrere Fälle, in denen das Relay eine unvollständige Antwort als vollständig meldete: ein fehlgeschlagener Datenbanklesevorgang beendete eine Abfrage, als wäre sie fertig, und eine Negentropy-Synchronisation konnte eine unvollständige Menge versiegeln, wodurch das Relay Ereignisse als fehlend meldete, die es tatsächlich besitzt. Einstellungen, die niemals wirksam werden können, werden beim Start mit einer Warnung abgelehnt, die sie benennt, statt stillschweigend akzeptiert zu werden. Das ist vor allem für die IP-Sperrliste wichtig, wo ein als CIDR-Bereich geschriebener Eintrag überhaupt nichts blockierte. Die Negentropy-Synchronisation großer Ereignismengen ist deutlich schneller, und eine Verbindung, deren Schreibvorgang fehlschlägt, wird jetzt geschlossen, statt einen beschädigten Datenstrom weiter zu empfangen.',
    pl_PL:
      'Aktualizuje wisp do v0.6.0, pomijając v0.5.15, które nigdy nie zostało spakowane. Dodaje watchdoga, który restartuje przekaźnik, jeśli jego pętla akceptowania przestanie przyjmować połączenia. Naprawia kilka przypadków, w których przekaźnik zgłaszał niepełną odpowiedź jako pełną: nieudany odczyt z bazy danych kończył zapytanie tak, jakby się zakończyło, a synchronizacja negentropy mogła zapieczętować niepełny zbiór, przez co przekaźnik zgłaszał jako brakujące zdarzenia, które w rzeczywistości posiadał. Ustawienia, które nigdy nie mogłyby zadziałać, są teraz odrzucane przy starcie z ostrzeżeniem wskazującym je z nazwy, zamiast być po cichu przyjmowane. Ma to największe znaczenie dla listy blokowanych adresów IP, gdzie wpis zapisany jako zakres CIDR nie blokował niczego. Synchronizacja negentropy dużych zbiorów zdarzeń jest znacznie szybsza, a połączenie, którego zapis się nie powiódł, jest teraz zamykane zamiast pozostawać z uszkodzonym strumieniem.',
    fr_FR:
      "Met à jour wisp vers v0.6.0, en sautant v0.5.15 qui n'a jamais été empaqueté. Ajoute une surveillance qui redémarre le relais si sa boucle d'acceptation cesse d'accepter les connexions. Corrige plusieurs cas où le relais signalait une réponse incomplète comme complète : une lecture de base de données en échec terminait une requête comme si elle avait abouti, et une synchronisation negentropy pouvait sceller un ensemble partiel, ce qui amenait le relais à signaler comme manquants des événements qu'il possédait réellement. Les paramètres qui ne pouvaient jamais prendre effet sont désormais refusés au démarrage avec un avertissement les nommant, au lieu d'être acceptés en silence ; cela compte surtout pour la liste de blocage d'IP, où une entrée écrite sous forme de plage CIDR ne bloquait rien. La synchronisation negentropy sur de grands ensembles d'événements est nettement plus rapide, et une connexion dont l'écriture échoue est maintenant fermée au lieu de rester à recevoir un flux corrompu.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: async ({ effects }) => {},
  },
})
